
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 28 00:53:30 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESSEQUALS = 50;
  public static final int GREATEREQUALS = 48;
  public static final int CONST = 37;
  public static final int EQUALS = 45;
  public static final int NAMESPACE = 28;
  public static final int NUMCONST = 3;
  public static final int GREATER = 47;
  public static final int HASH = 13;
  public static final int LPAREN = 21;
  public static final int CONTINUE = 25;
  public static final int LESS = 49;
  public static final int MINUS = 29;
  public static final int STATIC = 20;
  public static final int RPAREN = 22;
  public static final int SEMICOLON = 36;
  public static final int AND = 33;
  public static final int RANGE = 11;
  public static final int DOUBLEINC = 7;
  public static final int OR = 34;
  public static final int COMMA = 38;
  public static final int INC = 42;
  public static final int DIV = 30;
  public static final int PLUS = 17;
  public static final int IF = 39;
  public static final int EXCLAMATION = 12;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int NEW = 51;
  public static final int ISEQUAL = 35;
  public static final int RSBRACKET = 19;
  public static final int error = 1;
  public static final int PROGRAM = 14;
  public static final int MUL = 31;
  public static final int MOD = 32;
  public static final int BREAK = 23;
  public static final int IDENT = 2;
  public static final int VOID = 44;
  public static final int COLON = 26;
  public static final int LBRACE = 15;
  public static final int ELSE = 24;
  public static final int READ = 40;
  public static final int NOTEQUALS = 46;
  public static final int FINAL = 9;
  public static final int CHARCONST = 5;
  public static final int RBRACE = 16;
  public static final int BOOLCONST = 4;
  public static final int FULLSTOP = 10;
  public static final int DEC = 43;
  public static final int COUNT = 8;
  public static final int PRINT = 41;
  public static final int LSBRACKET = 18;
  public static final int DOUBLECOLON = 6;
}

